# Generated by Django 4.2 on 2023-04-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_admin_remove_userinfo_account_remove_userinfo_depart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('time', models.DateField(primary_key=True, serialize=False, verbose_name='日期')),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='温度')),
                ('ph', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ph值')),
                ('weather', models.CharField(max_length=32, verbose_name='天气')),
            ],
        ),
    ]
